/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:3137c9aa-ae87-4d9d-afac-8e55d699902e",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_2Jf0U6Wet",
    "aws_user_pools_web_client_id": "5kb9f4sobeeojipe8df2juop00",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://mzrfsnf67rep5bsz3l3zthhyty.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
